server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**

    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

endpoint:
  health:
    show-details: always

# Test property → kontrol etmek için loga bastıracağız
my:
  test-property: HelloFromConfigServer-ApiGateway
