management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
my:
  test-property: HelloFromSharedConfig
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true