spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  profiles: shared-config

my:
  test-property: HelloFromSharedConfig