server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/astralx_transactiondb
    username: bankuser
    password: bankpass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
      config:
        fail-fast: true
